# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24934a6462126fe52757b87ed288cf405eb74899effde1d67926a507de38dcea92a8bf95903e768c3a5bdf6e07492932dfb7b8d7aaa9aff753ee9dd9b2a8e7ba

test:
  secret_key_base: e10c586ca11361445b314a0196e180f24161ddb690c0d9af8df3c900106214cc74fe72229cc9eb301e8343f267eac2df2ef634c9636252c72547de5d02b02899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
